plugins { id 'com.android.application' }

android {
    namespace 'com.example.catresolutionclone'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.catresolutionclone'
        minSdk 23
        targetSdk 29
        versionCode 3
        versionName '3.0'
    }
}

dependencies {
}
